planner_id: Smac2D
names:
- wp_05
- wp_07
- wp_08
- wp_09
- wp_10
- wp_11
- wp_12
- wp_13
- wp_14
- wp_15
- wp_16
- wp_17
- wp_18
- wp_19
- wp_20
- wp_21
- wp_22
- wp_23
- wp_25
route_solver: pulp_cbc_milp
route_time_limit_sec: 120.0
milp_gap_rel: 0.0
routes_by_first:
  wp_05:
    route:
    - wp_05
    - wp_08
    - wp_10
    - wp_09
    - wp_07
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_15
    - wp_11
    - wp_14
    - wp_17
    - wp_18
    - wp_23
    - wp_21
    - wp_20
    - wp_22
    - wp_25
    cost: 147.9738
    edge_costs:
    - 3.3643
    - 8.1914
    - 10.8274
    - 7.7022
    - 11.9464
    - 7.4113
    - 7.6185
    - 7.5223
    - 9.4134
    - 9.3405
    - 8.5702
    - 8.6984
    - 7.25
    - 11.5609
    - 7.3168
    - 10.3941
    - 7.5652
    - 3.2805
    solver_status: Optimal
    optimality_proven: true
  wp_07:
    route:
    - wp_07
    - wp_12
    - wp_09
    - wp_08
    - wp_05
    - wp_10
    - wp_11
    - wp_14
    - wp_17
    - wp_15
    - wp_13
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    cost: 139.3176
    edge_costs:
    - 11.9464
    - 5.3451
    - 7.5805
    - 3.5416
    - 11.1234
    - 7.4
    - 8.5702
    - 8.6984
    - 9.3349
    - 8.9942
    - 7.6185
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    solver_status: Optimal
    optimality_proven: true
  wp_08:
    route:
    - wp_08
    - wp_05
    - wp_10
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_15
    - wp_11
    - wp_14
    - wp_17
    - wp_18
    - wp_23
    - wp_21
    - wp_22
    - wp_25
    - wp_20
    cost: 147.2735
    edge_costs:
    - 3.5416
    - 11.1234
    - 16.495
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    - 7.5223
    - 9.4134
    - 9.3405
    - 8.5702
    - 8.6984
    - 7.25
    - 11.5609
    - 7.3168
    - 6.5384
    - 3.2805
    - 8.7725
    solver_status: Optimal
    optimality_proven: true
  wp_09:
    route:
    - wp_09
    - wp_12
    - wp_07
    - wp_08
    - wp_05
    - wp_10
    - wp_11
    - wp_14
    - wp_17
    - wp_15
    - wp_13
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    cost: 142.1725
    edge_costs:
    - 5.3217
    - 11.8988
    - 10.5064
    - 3.5416
    - 11.1234
    - 7.4
    - 8.5702
    - 8.6984
    - 9.3349
    - 8.9942
    - 7.6185
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    solver_status: Optimal
    optimality_proven: true
  wp_10:
    route:
    - wp_10
    - wp_05
    - wp_08
    - wp_09
    - wp_07
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_15
    - wp_11
    - wp_14
    - wp_17
    - wp_18
    - wp_23
    - wp_21
    - wp_22
    - wp_25
    - wp_20
    cost: 145.0101
    edge_costs:
    - 11.123
    - 3.3643
    - 7.5805
    - 7.7022
    - 11.9464
    - 7.4113
    - 7.6185
    - 7.5223
    - 9.4134
    - 9.3405
    - 8.5702
    - 8.6984
    - 7.25
    - 11.5609
    - 7.3168
    - 6.5384
    - 3.2805
    - 8.7725
    solver_status: Optimal
    optimality_proven: true
  wp_11:
    route:
    - wp_11
    - wp_10
    - wp_08
    - wp_05
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_15
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    - wp_17
    - wp_14
    cost: 134.0017
    edge_costs:
    - 7.4
    - 8.1595
    - 3.5416
    - 13.3348
    - 7.4981
    - 5.3217
    - 7.4113
    - 8.9555
    - 7.2151
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    - 7.25
    - 8.7497
    solver_status: Optimal
    optimality_proven: true
  wp_12:
    route:
    - wp_12
    - wp_07
    - wp_09
    - wp_08
    - wp_05
    - wp_10
    - wp_11
    - wp_14
    - wp_17
    - wp_15
    - wp_13
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    cost: 141.423
    edge_costs:
    - 11.8988
    - 7.4981
    - 7.5805
    - 3.5416
    - 11.1234
    - 7.4
    - 8.5702
    - 8.6984
    - 9.3349
    - 8.9942
    - 7.6185
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    solver_status: Optimal
    optimality_proven: true
  wp_13:
    route:
    - wp_13
    - wp_12
    - wp_09
    - wp_07
    - wp_05
    - wp_08
    - wp_10
    - wp_11
    - wp_15
    - wp_14
    - wp_17
    - wp_18
    - wp_21
    - wp_23
    - wp_22
    - wp_25
    - wp_20
    - wp_19
    - wp_16
    cost: 136.046
    edge_costs:
    - 7.4113
    - 5.3451
    - 7.7022
    - 13.2963
    - 3.3643
    - 8.1914
    - 7.4
    - 9.2252
    - 8.9222
    - 8.6984
    - 7.25
    - 5.1435
    - 7.4111
    - 9.2292
    - 3.2805
    - 8.7725
    - 7.9346
    - 7.4682
    solver_status: Optimal
    optimality_proven: true
  wp_14:
    route:
    - wp_14
    - wp_15
    - wp_19
    - wp_16
    - wp_13
    - wp_12
    - wp_07
    - wp_09
    - wp_08
    - wp_05
    - wp_10
    - wp_11
    - wp_17
    - wp_18
    - wp_23
    - wp_21
    - wp_22
    - wp_25
    - wp_20
    cost: 148.7969
    edge_costs:
    - 8.9222
    - 9.4914
    - 7.4682
    - 7.7845
    - 7.4113
    - 11.8988
    - 7.4981
    - 7.5805
    - 3.5416
    - 11.1234
    - 7.4
    - 13.9578
    - 7.25
    - 11.5609
    - 7.3168
    - 6.5384
    - 3.2805
    - 8.7725
    solver_status: Optimal
    optimality_proven: true
  wp_15:
    route:
    - wp_15
    - wp_17
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    cost: 136.2447
    edge_costs:
    - 9.4274
    - 8.7497
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    solver_status: Optimal
    optimality_proven: true
  wp_16:
    route:
    - wp_16
    - wp_15
    - wp_17
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_23
    - wp_18
    cost: 141.3993
    edge_costs:
    - 7.2151
    - 9.4274
    - 8.7497
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 13.9581
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 0.0
    - 11.547
    solver_status: Optimal
    optimality_proven: true
  wp_17:
    route:
    - wp_17
    - wp_14
    - wp_15
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    cost: 136.5174
    edge_costs:
    - 8.7497
    - 8.9222
    - 9.3405
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    solver_status: Optimal
    optimality_proven: true
  wp_18:
    route:
    - wp_18
    - wp_21
    - wp_23
    - wp_22
    - wp_25
    - wp_20
    - wp_19
    - wp_15
    - wp_17
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    cost: 138.2651
    edge_costs:
    - 5.1435
    - 7.4111
    - 9.2292
    - 3.2805
    - 8.7725
    - 7.9346
    - 9.4134
    - 9.4274
    - 8.7497
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    solver_status: Optimal
    optimality_proven: true
  wp_19:
    route:
    - wp_19
    - wp_15
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    cost: 136.4032
    edge_costs:
    - 9.4134
    - 8.9222
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    - 7.5223
    - 7.9346
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    solver_status: Optimal
    optimality_proven: true
  wp_20:
    route:
    - wp_20
    - wp_25
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    - wp_17
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    - wp_15
    cost: 135.5461
    edge_costs:
    - 8.7725
    - 3.2247
    - 9.2855
    - 7.3168
    - 5.108
    - 7.25
    - 8.7497
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    - 7.5223
    - 9.4134
    solver_status: Optimal
    optimality_proven: true
  wp_21:
    route:
    - wp_21
    - wp_18
    - wp_23
    - wp_22
    - wp_25
    - wp_20
    - wp_19
    - wp_16
    - wp_13
    - wp_15
    - wp_17
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    cost: 142.1444
    edge_costs:
    - 5.108
    - 11.5609
    - 9.2292
    - 3.2805
    - 8.7725
    - 7.9346
    - 7.4682
    - 7.7845
    - 8.9555
    - 9.4274
    - 8.7497
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    solver_status: Optimal
    optimality_proven: true
  wp_22:
    route:
    - wp_22
    - wp_18
    - wp_20
    - wp_21
    - wp_23
    - wp_18
    - wp_17
    - wp_14
    - wp_15
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    - wp_16
    - wp_19
    cost: 158.9831
    edge_costs:
    - 12.0066
    - 15.4745
    - 10.4186
    - 7.4111
    - 11.547
    - 7.25
    - 8.7497
    - 8.9222
    - 9.3405
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    - 7.6185
    - 7.5223
    solver_status: Optimal
    optimality_proven: true
  wp_23:
    route:
    - wp_23
    - wp_18
    - wp_21
    - wp_22
    - wp_25
    - wp_20
    - wp_19
    - wp_16
    - wp_15
    - wp_17
    - wp_14
    - wp_11
    - wp_10
    - wp_05
    - wp_08
    - wp_07
    - wp_09
    - wp_12
    - wp_13
    cost: 137.3616
    edge_costs:
    - 11.547
    - 5.1435
    - 6.5384
    - 3.2805
    - 8.7725
    - 7.9346
    - 7.4682
    - 7.2151
    - 9.4274
    - 8.7497
    - 8.5626
    - 7.4
    - 11.123
    - 3.3643
    - 10.6037
    - 7.4981
    - 5.3217
    - 7.4113
    solver_status: Optimal
    optimality_proven: true
  wp_25:
    route:
    - wp_25
    - wp_20
    - wp_22
    - wp_23
    - wp_21
    - wp_18
    - wp_17
    - wp_14
    - wp_15
    - wp_19
    - wp_16
    - wp_13
    - wp_12
    - wp_09
    - wp_07
    - wp_08
    - wp_05
    - wp_10
    - wp_11
    cost: 140.744
    edge_costs:
    - 8.7725
    - 7.5652
    - 9.2855
    - 7.3168
    - 5.108
    - 7.25
    - 8.7497
    - 8.9222
    - 9.4914
    - 7.4682
    - 7.7845
    - 7.4113
    - 5.3451
    - 7.7022
    - 10.5064
    - 3.5416
    - 11.1234
    - 7.4
    solver_status: Optimal
    optimality_proven: true
